### ISSUE TITLE
Kivy 101 Workshop

### ISSUE THREAD

**Issue by akshayaurora** [pydelhi/workshops#1]
https://docs.google.com/presentation/d/1zoyqnnDqpXRPmZ1pLYu05cWMg-l9qt2657uGFozZWig

I will be holding the workshop if there are enough votes, it is the same presentation I held on PyCon last year https://in.pycon.org/funnel/2014/220-mobile-application-development-with-python-kivy/

@amitt001 and a couple of other people showed interested in this. If we have enough people interested I would love doing this workshop.

Prerequisites for this work shop::

```
Make sure you have kivy installed on your os http://kivy.org/#download
```

Ref: https://github.com/pydelhi/talks/issues/4

**Comment by amitt001** [comment]
:+1:

**Comment by akshayaurora** [comment]
This workshop was concluded on our last meet on JNU
