### ISSUE TITLE
Workshop Proposal: Symbolic Computation with Python using SymPy

### ISSUE THREAD

**Issue by aktech** [pydelhi/workshops#4]
I am proposing a workshop for PyDelhi's Upcoming Meetup. Since the workshop for 16 Jan is already taken, the day of next meetup would be great for this workshop.

**Slides:**
http://iamit.in/talks/slides/sympy-tutorial-intro.pdf

**Ipython-Notebooks:**
http://iamit.in/sympy-tutorial/tutorial_exercises.zip

**Comment by akshayaurora** [comment]
+1 for 6th feb
